[[redirects]]
  from = "/"
  to = "/swap"
  status = 200
  force = true # COMMENT: ensure that we always redirect
[[redirects]]
  from = "/_next/static/index-*"
  to = "/swap"
  status = 200
  force = true # COMMENT: ensure that we always redirect